#!/usr/bin/env bash
set -e

usage() {
cat << EOF
USAGE:
  vwc [all|category|"*.md"]
EXAMPLES:
  vwc ./some-arcane-topic.md
    compiles some-arcane-topic
  vwc category
    1) /home/lynx/Dropbox/wiki/academics
    2) /home/lynx/Dropbox/wiki/coding
    3) /home/lynx/Dropbox/wiki/diary
    4) /home/lynx/Dropbox/wiki/cheats
    5) /home/lynx/Dropbox/wiki/books
    #? 2

    compiles notes in 2)
  vwc all
    compiles all notes

EOF
}

STATIC="$HOME/repositories/vwc/static"
BIN="$HOME/repositories/vwc/bin"

makepdf() {
  bib="$2.bib"

  if [ -f "$bib" ]; then
    echo "Found $bib"
    pandoc "$STATIC/meta.yml" \
      --from markdown+implicit_figures \
      --include-in-header "$STATIC/header.tex" \
      --template "$STATIC/notes.tex" \
      --filter "$BIN/pandocCommentFilter.py" \
      --toc \
      --bibliography "$bib" \
      --filter pandoc-citeproc --csl "$STATIC/ieee-with-url.csl" \
      -o "$2.pdf" $1 && echo "Created $2.pdf"
  else
    pandoc "$STATIC/meta.yml" \
      --from markdown+implicit_figures \
      --include-in-header "$STATIC/header.tex" \
      --template="$STATIC/notes.tex" \
      --filter "$BIN/pandocCommentFilter.py" \
      --toc \
      -o "$2.pdf" $1 && echo "Created $2.pdf"
  fi
}

makehtml() {
  bib="$2.bib"

  if [ -f "$bib" ]; then
    echo "Found $bib"
    pandoc "$STATIC/meta.yml" \
    --template="$STATIC/notes.html" \
    --filter "$BIN/pandocCommentFilter.py" \
    --toc \
    --katex \
    --bibliography "$bib" \
    --filter pandoc-citeproc --csl "$STATIC/ieee-with-url.csl" \
    -c "$STATIC/tufte.css" \
    -o "$2.html" $1 && echo "Created $2.html"
  else
    pandoc "$STATIC/meta.yml" \
    --template="$STATIC/notes.html" \
    --filter "$BIN/pandocCommentFilter.py" \
    --toc \
    --katex \
    -c "$STATIC/tufte.css"  \
    -o "$2.html" $1 && echo "Created $2.html"
  fi


}


makenotes() {
  ## Recursively cd into categories until there's no more directories left
  ## then compile the notes in that directory and combines pdfs with gs
  unset categories files output input

  categories=$(find $1 -mindepth 1 \
    -maxdepth 1 -type d ! -name "static")

  if [ -z "$categories" ]
  then
    cd "$1"
    files=$(find . -mindepth 1 -maxdepth 1 -type f \
      ! \( -name "index.md" -or -name "*.log" -or \
      -name "*.pdf" -or -name "*.html" -or \
      -name "diary.md" or -name "*.bib" \) )

    for notes in $files;do
      input="$1/$(basename $notes)"
      output="$1/$(basename $input .md)"
      makehtml "$input" "$output"
      makepdf "$input" "$output"
    done

    makehtml "$files" "$(basename $1)"
    makepdf "$files" "$(basename $1)"

    cd - &>/dev/null
  else
    for category in $categories;do
        makenotes "$category"
    done
  fi
}


# https://askubuntu.com/questions/682095/create-bash-menu-based-on-file-list-map-files-to-numbers
selectcategory() {
  unset options i
  while IFS= read -r -d $'\0' f; do
    options[i++]="$f"
  done < <(find $WIKI_PATH -maxdepth 1 -mindepth 1 -type d ! -name "static" -print0 )

  N=${#options[@]}

  select opt in "${options[@]}"; do
    case $REPLY in
      [1-$N])
        cat="$opt"
        break
        ;;
      *)
        echo "Invalid input"
        exit 0
        ;;
    esac
  done

  unset N options i opt
}

main() {
  case "$1" in
    "all")
      echo "compiling all notes..."
      makenotes $WIKI_PATH
      ;;
    "category")
      selectcategory
      echo "compiling category $cat..."
      makenotes $cat
      unset cat
      ;;
    *.md)
      fn="$(basename $1 .md)"
      dir="$(dirname $1)"
      echo "compiling a single file $1"
      makehtml "$1" "$dir/$fn"
      makepdf "$1" "$dir/$fn"
      unset fn dir
      ;;
    *)
      usage
      ;;
  esac
}

main $1
