---
documentclass: tufte-handout
mainfont: Palatino Linotype
sansfont: Optima
monofont: Iosevka
tocdepth: 3
numbersections: true
linktoc: all
linkcolor: RoyalBlue
urlcolor: RoyalBlue
toccolor: RoyalBlue
highlight-style: monochrome
newtxmathoptions:
- cmintegrals
- cmbraces
subparagraph: yes
---
