---
mainfont: Palatino Linotype
sansfont: Optima
monofont: Iosevka
tocdepth: 3
numbersections: true
linktoc: all
citecolor: TeXRed
filecolor: TeXRed
linkcolor: TeXRed
urlcolor: TeXRed
toccolor: TeXRed
allbordercolors: TeXRed
urlbordercolor: TeXRed
highlight-style: monochrome
---
